apiVersion: v1
kind: Service
metadata:
  name: aspnetcore-service
  labels:
    app: aspnetcore
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: aspnetcore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-v1
spec:
  selector:

    matchLabels:

      app: aspnetcore
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnetcore
        version: v1
    spec:
      containers:
      - name: aspnetcore
        image: eswaribala/rpsallsecrepo:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: MSSQL_HOST
            value: "127.0.0.1"
          - name: MSSQL_PORT
            value: "1433"
          - name: MSSQL_DATABASE
            value: RPSDB
          - name: SA_PASSWORD
            value: Vignesh@95